### ISSUE TITLE
react hook warning

### ISSUE THREAD

**Issue by mattetti** [nmetulev/graph-react-starter#1]
./src/mgt.ts
  Line 58:6:  React Hook useEffect has missing dependencies: 'deps' and 'options'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by nmetulev** [comment]
Added the ignore line for now to remove the warning
