### ISSUE TITLE
Build gives a warning which prevents seeing the URL in Github Codespaces

### ISSUE THREAD

**Issue by DanWahlin** [nmetulev/graph-react-starter#4]
After running `yarn start` in Github Codespaces a warning appears due to `deps` and `options` not being passed into the useGet hook dependency list. That blocked seeing the URL that I need to click for the forwarding Codespaces does.

I updated the useGet dependencies to `[isSignedIn, resource, deps, options]` and the warning went away. Haven't look if adding those breaks anything else though.

**Comment by nmetulev** [comment]
I'm added a temporary compiler directive to ignore the warning - let me know if that doesn't work.
